services:
  web:
    image: yogeshdharya/website-nginx:latest
    container_name: website_nginx
    ports:
      - "80:80"
    restart: always
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_MONITOR_ONLY=false
    restart: always
    profiles:
      - "tools"