---
- name: Deploy Dockerized Website
  hosts: webserver
  become: true
  tasks:

    - name: Ensure apt cache is up to date (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker (if not already installed)
      ansible.builtin.package:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: yogeshdharya/website-nginx:latest
        source: pull

    - name: Run Prachi Website container
      community.docker.docker_container:
        name: website
        image: yogeshdharya/website-nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
